import { Poppins } from "next/font/google";
import "./globals.css";
import Pagination from "./components/Pagination";
import { Suspense } from "react";

const poppins = Poppins({ weight: ["400", "500", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Profile | Users List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} p-5 w-full`}>
        <h2 className="text-4xl font-light">Users List</h2>
        {children}
      </body>
    </html>
  );
}
